### ISSUE TITLE
Initial Code Review

### ISSUE THREAD

**Issue by rachelkelly** [Brightmd/txk8s#1]

**Comment by corydodt** [comment]
- add tox to your requirements.txt

**Comment by corydodt** [comment]
```
txk8s/__init__.py:5: in <module>
    from txk8s import (_version,
```
This won't work, you're importing from the same module that contains the import statement.

**Comment by corydodt** [comment]
Let's add a brief API reference and a simple example to the README. Also a note of some kind about the prerequisite of having authentication (.kube folder or other solution).

- API reference can just be just a list of methods with the arguments they take + docstring
- Example can just be 4 lines of code, doesn't have to be a complete program. Assuming the reactor is already running and auth is set up, instantiate a client and use it to grab a secret.
- Authenetication note. Can be a link to a more complete reference.

**Comment by corydodt** [comment]
- Missing test requirement, mock

**Comment by corydodt** [comment]
Need twisted = 1 in `pytest.ini`. In fact, all new open source projects we release should turn this on if they have twisted in requirements.txt.

**Comment by corydodt** [comment]
`/Users/cory/src/txk8s/txk8s/test/test_lib.py:287: UndefinedName
undefined name 'txkube'`

**Comment by corydodt** [comment]
In `__init__.py` you need to add (foo, bar, ) for all the unused imports, pyflakes won't pass otherwise. 

https://github.com/Brightmd/hoursofoperation/blob/master/hoursofoperation/__init__.py#L10

**Comment by corydodt** [comment]
E       fixture 'kubeConfig' not found

I think you need to copy jessica's `conftest.py`, or at least parts of it. It can go in txk8s/test/

**Comment by corydodt** [comment]
html_tmp and Library in `.gitignore`

**Comment by corydodt** [comment]
`setup.py`'s `install_requires`_ and `requirements.txt` should be a little looser around versions.

I suggest
- `kubernetes>=3.0.0,<3.1.0`
- `pyyaml>=3.10,<4.0.0`
- `Twisted>=16.0.0,<18.0.0`

This will allow more people to install this software without patching anything.

**Comment by rachelkelly** [comment]
Also adding `conftest.py`

**Comment by corydodt** [comment]
I added an example with a PR from corydodt/txk8s and at this point I'm fine with deferring the other two doc notes until later:
- api reference in readme,
- authentication notes

**Comment by rachelkelly** [comment]
All changes made
